version: 1.0.{build}
image: Ubuntu2204
branches:
  only:
  - master

# Set environment
environment:
  MLE_ROOT: /opt/MagicLantern

# Install dependencies
install:
- sh: >-
    sudo mkdir $MLE_ROOT;
    git clone -q --branch=master https://github.com/magic-lantern-studio/mle-core-util.git /home/appveyor/projects/mle-core-util;
    cd /home/appveyor/projects/mle-core-util/util/linux/build;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    git clone -q --branch=master https://github.com/magic-lantern-studio/mle-core-math.git /home/appveyor/projects/mle-core-math;
    cd /home/appveyor/projects/mle-core-math/math/linux/libmlmath;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install

# Custom script to build libmlmath.so using autoconf tools.
build_script:
- sh: >-
    cd /home/appveyor/projects/mle-core-dwp/DigitalWorkprint/lib/linux;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-util/util/linux/build;
    sudo MLE_ROOT=$MLE_ROOT make uninstall;
    cd /home/appveyor/projects/mle-core-math/math/linux/libmlmath;
    sudo MLE_ROOT=$MLE_ROOT make uninstall

# Custom script to create an .zip file containing the libDWP artifacts.
after_build:
- sh: >-
    cd /home/appveyor/projects/mle-core-dwp;
    7z a mldwp.zip $MLE_ROOT

# Define artifacts to push to AppVeyor
artifacts:
- path: mldwp.zip
  name: mle-core-dwp
